export const decisions = [
  { id: 1, title: 'Khẳng định tuyệt đối', message: 'Không còn nghi ngờ gì nữa.' },
  {
    id: 2,
    title: 'Khuyến khích hành động',
    message: 'Hãy dứt khoát tiến lên và thực hiện ngay đi.',
  },
  {
    id: 3,
    title: 'Lời khuyên kiên nhẫn',
    message: 'Bây giờ chưa phải là thời điểm thích hợp, hãy kiên nhẫn chờ đợi.',
  },
  { id: 4, title: 'Sự cẩn trọng', message: 'Đừng đặt cược hay kỳ vọng quá nhiều vào điều đó.' },
  {
    id: 5,
    title: 'Lắng nghe bản thân',
    message: 'Hãy tin tưởng hoàn toàn vào trực giác của bạn lúc này.',
  },
  {
    id: 6,
    title: 'Chấp nhận thực tế',
    message: 'Vấn đề này đã nằm ngoài tầm kiểm soát của bạn rồi.',
  },
  {
    id: 7,
    title: 'Góc nhìn mới',
    message: 'Hãy thử tiếp cận và giải quyết theo một hướng hoàn toàn khác.',
  },
  { id: 8, title: 'Bất ngờ phía trước', message: 'Bạn sẽ nhận được một sự ngạc nhiên đầy thú vị.' },
  {
    id: 9,
    title: 'Tránh lãng phí năng lượng',
    message: 'Đừng lãng phí thời gian của bạn cho việc này nữa.',
  },
  { id: 10, title: 'Sự đồng thuận', message: 'Chắc chắn là như vậy.' },
  { id: 11, title: 'Kết quả tích cực', message: 'Kết quả sẽ vô cùng tốt đẹp.' },
  { id: 12, title: 'Sự chắc chắn', message: 'Bạn có thể tin tưởng vào điều đó.' },
  { id: 13, title: 'Cơ hội tốt', message: 'Đó là một cơ hội tuyệt vời, đừng bỏ lỡ.' },
  { id: 14, title: 'Đồng tình', message: 'Hoàn toàn đồng ý.' },
  { id: 15, title: 'Tính khả thi', message: 'Mọi thứ đang đi đúng hướng.' },
  { id: 16, title: 'Lời đáp mở', message: 'Câu trả lời là Có.' },
  { id: 17, title: 'Sự ủng hộ', message: 'Những người xung quanh sẽ ủng hộ bạn.' },
  { id: 18, title: 'Khẳng định mạnh', message: 'Tuyệt đối chính xác.' },
  { id: 19, title: 'Tín hiệu vui', message: 'Một tin vui đang đến gần.' },
  { id: 20, title: 'Niềm tin', message: 'Hãy giữ vững niềm tin, bạn đang làm đúng.' },
  { id: 21, title: 'Từ chối', message: 'Câu trả lời là Không.' },
  { id: 22, title: 'Phủ định mạnh', message: 'Tuyệt đối không nên làm vậy.' },
  { id: 23, title: 'Rủi ro cao', message: 'Rủi ro quá lớn, hãy dừng lại.' },
  { id: 24, title: 'Cảnh báo', message: 'Đó không phải là một ý kiến hay.' },
  { id: 25, title: 'Lời khuyên từ bỏ', message: 'Tốt nhất là bạn nên từ bỏ ý định này.' },
  { id: 26, title: 'Thiếu khả thi', message: 'Điều này rất khó có thể xảy ra.' },
  { id: 27, title: 'Trở ngại', message: 'Sẽ có rất nhiều trở ngại phía trước.' },
  { id: 28, title: 'Kết quả không như ý', message: 'Bạn sẽ phải thất vọng đấy.' },
  { id: 29, title: 'Hành động sai lầm', message: 'Đừng mắc sai lầm ngớ ngẩn này.' },
  { id: 30, title: 'Lời khuyên lùi bước', message: 'Hãy lùi lại một bước và nhìn nhận lại.' },
  { id: 31, title: 'Sự trì hoãn', message: 'Hãy để việc này lại sau.' },
  {
    id: 32,
    title: 'Lắng nghe ý kiến',
    message: 'Bạn cần xin lời khuyên từ một người có kinh nghiệm.',
  },
  { id: 33, title: 'Câu trả lời chưa rõ', message: 'Mọi thứ vẫn còn quá mờ mịt.' },
  { id: 34, title: 'Bình tĩnh', message: 'Đừng vội vã, hãy hít thở thật sâu.' },
  { id: 35, title: 'Cần thêm thông tin', message: 'Bạn chưa có đủ thông tin để quyết định.' },
  {
    id: 36,
    title: 'Thời gian trả lời',
    message: 'Thời gian sẽ cho bạn câu trả lời chính xác nhất.',
  },
  { id: 37, title: 'Tạm dừng', message: 'Hãy tạm dừng mọi thứ lại trong chốc lát.' },
  { id: 38, title: 'Chưa đến lúc', message: 'Vẫn còn quá sớm để nói trước điều gì.' },
  { id: 39, title: 'Chờ đợi cơ hội', message: 'Một cơ hội tốt hơn đang ở phía sau.' },
  { id: 40, title: 'Cân nhắc kỹ', message: 'Hãy suy nghĩ thêm một vài ngày nữa.' },
  { id: 41, title: 'Hành động cẩn trọng', message: 'Hãy bước đi thật chậm rãi và cẩn thận.' },
  { id: 42, title: 'Lưu ý tiểu tiết', message: 'Đừng bỏ qua những chi tiết nhỏ nhặt.' },
  { id: 43, title: 'Tìm hiểu sâu', message: 'Hãy đào sâu hơn vào vấn đề này.' },
  { id: 44, title: 'Rà soát lại', message: 'Kiểm tra lại mọi thứ một lần nữa.' },
  { id: 45, title: 'Tránh bốc đồng', message: 'Đừng để cảm xúc lấn át lý trí của bạn.' },
  { id: 46, title: 'Kế hoạch dự phòng', message: 'Bạn cần chuẩn bị sẵn một kế hoạch B.' },
  { id: 47, title: 'Cẩn thận lời nói', message: 'Hãy cẩn trọng với những gì bạn sắp nói ra.' },
  { id: 48, title: 'Giữ bí mật', message: 'Đừng tiết lộ điều này cho bất kỳ ai vào lúc này.' },
  {
    id: 49,
    title: 'Tiết kiệm sức lực',
    message: 'Hãy giữ lại năng lượng cho những việc quan trọng hơn.',
  },
  { id: 50, title: 'Đánh giá rủi ro', message: 'Hãy cân nhắc kỹ những rủi ro có thể gặp phải.' },
  { id: 51, title: 'Sẵn sàng', message: 'Mọi thứ đã sẵn sàng, hãy bắt đầu thôi.' },
  { id: 52, title: 'Chủ động', message: 'Bạn phải là người chủ động trong việc này.' },
  { id: 53, title: 'Dốc toàn lực', message: 'Hãy nỗ lực hết mình, đừng giữ lại gì cả.' },
  { id: 54, title: 'Đưa ra lựa chọn', message: 'Đã đến lúc bạn phải đưa ra quyết định cuối cùng.' },
  { id: 55, title: 'Vượt qua nỗi sợ', message: 'Đừng để nỗi sợ hãi cản bước chân bạn.' },
  { id: 56, title: 'Thay đổi', message: 'Bạn cần tạo ra một sự thay đổi lớn.' },
  { id: 57, title: 'Làm mới bản thân', message: 'Hãy rũ bỏ quá khứ và bắt đầu lại.' },
  { id: 58, title: 'Giải quyết dứt điểm', message: 'Hãy kết thúc việc này một lần và mãi mãi.' },
  { id: 59, title: 'Hợp tác', message: 'Bạn cần hợp tác với người khác để thành công.' },
  { id: 60, title: 'Yêu cầu giúp đỡ', message: 'Đừng ngại mở lời xin sự giúp đỡ.' },
  { id: 61, title: 'Lắng nghe con tim', message: 'Trái tim bạn đã biết rõ câu trả lời.' },
  {
    id: 62,
    title: 'Tin vào linh cảm',
    message: 'Linh cảm của bạn về chuyện này là hoàn toàn đúng.',
  },
  { id: 63, title: 'Thành thật với bản thân', message: 'Hãy tự hỏi xem bạn thực sự muốn gì.' },
  {
    id: 64,
    title: 'Giá trị cốt lõi',
    message: 'Hãy hành động theo đúng giá trị và niềm tin của bạn.',
  },
  { id: 65, title: 'Tự tin lên', message: 'Bạn giỏi hơn bạn nghĩ rất nhiều.' },
  { id: 66, title: 'Tha thứ', message: 'Hãy học cách tha thứ cho bản thân và người khác.' },
  { id: 67, title: 'Buông bỏ', message: 'Đã đến lúc phải buông tay rồi.' },
  {
    id: 68,
    title: 'Chăm sóc bản thân',
    message: 'Hãy dành thời gian chăm sóc sức khỏe tinh thần của bạn.',
  },
  { id: 69, title: 'Niềm vui nhỏ', message: 'Hãy tìm kiếm niềm vui từ những điều giản dị nhất.' },
  { id: 70, title: 'Biết ơn', message: 'Hãy trân trọng những gì bạn đang có.' },
  { id: 71, title: 'Góc nhìn tích cực', message: 'Hãy nhìn nhận vấn đề theo hướng tích cực hơn.' },
  { id: 72, title: 'Thỏa hiệp', message: 'Bạn sẽ phải nhượng bộ một chút trong chuyện này.' },
  { id: 73, title: 'Mở rộng tầm mắt', message: 'Hãy bước ra khỏi vùng an toàn của bạn.' },
  {
    id: 74,
    title: 'Sự linh hoạt',
    message: 'Đừng quá cứng nhắc, hãy linh hoạt thay đổi theo tình hình.',
  },
  {
    id: 75,
    title: 'Đánh giá khách quan',
    message: 'Hãy đặt mình vào vị trí của người khác để suy nghĩ.',
  },
  { id: 76, title: 'Sự sáng tạo', message: 'Hãy giải quyết vấn đề bằng sự sáng tạo của bạn.' },
  { id: 77, title: 'Phá vỡ quy tắc', message: 'Đôi khi bạn cần phải phá vỡ một vài quy tắc.' },
  {
    id: 78,
    title: 'Đơn giản hóa',
    message: 'Đừng làm mọi chuyện phức tạp thêm, hãy giữ nó đơn giản.',
  },
  { id: 79, title: 'Tập trung', message: 'Hãy tập trung vào mục tiêu chính, đừng xao nhãng.' },
  { id: 80, title: 'Trật tự', message: 'Bạn cần sắp xếp lại cuộc sống của mình.' },
  { id: 81, title: 'Sự thật', message: 'Sự thật cuối cùng sẽ được phơi bày.' },
  { id: 82, title: 'Nhân quả', message: 'Mọi hành động đều có hậu quả của nó.' },
  { id: 83, title: 'Sự công bằng', message: 'Công lý sẽ được thực thi.' },
  { id: 84, title: 'May mắn', message: 'Hôm nay là một ngày may mắn của bạn.' },
  { id: 85, title: 'Xui xẻo', message: 'Có vẻ như may mắn không mỉm cười với bạn lúc này.' },
  { id: 86, title: 'Tùy duyên', message: 'Chuyện gì đến sẽ đến, đừng gượng ép.' },
  { id: 87, title: 'Định mệnh', message: 'Đó là điều đã được sắp đặt sẵn.' },
  { id: 88, title: 'Phép màu', message: 'Hãy tin vào những phép màu trong cuộc sống.' },
  { id: 89, title: 'Giấc mơ', message: 'Giấc mơ của bạn sắp trở thành hiện thực.' },
  { id: 90, title: 'Bình yên', message: 'Bạn sẽ tìm thấy sự bình yên trong tâm hồn.' },
  { id: 91, title: 'Kỷ niệm', message: 'Đó sẽ là một kỷ niệm khó quên.' },
  { id: 92, title: 'Tình yêu', message: 'Tình yêu sẽ dẫn lối cho bạn.' },
  { id: 93, title: 'Tình bạn', message: 'Một người bạn cũ sẽ mang đến giải pháp.' },
  { id: 94, title: 'Tiền bạc', message: 'Vấn đề tài chính của bạn sẽ sớm được giải quyết.' },
  { id: 95, title: 'Công việc', message: 'Một bước tiến mới trong sự nghiệp đang chờ đón.' },
  { id: 96, title: 'Sức khỏe', message: 'Sức khỏe của bạn là ưu tiên hàng đầu lúc này.' },
  { id: 97, title: 'Gia đình', message: 'Gia đình sẽ luôn ở bên và hỗ trợ bạn.' },
  { id: 98, title: 'Chuyến đi', message: 'Một chuyến đi xa sẽ giúp bạn giải tỏa tâm trí.' },
  { id: 99, title: 'Học hỏi', message: 'Bạn sẽ rút ra được một bài học quý giá từ chuyện này.' },
  { id: 100, title: 'Kết thúc tốt đẹp', message: 'Mọi chuyện rồi sẽ ổn thôi.' },
  { id: 101, title: 'Khởi đầu mới', message: 'Hãy dọn đường cho một sự khởi đầu hoàn toàn mới.' },
  { id: 102, title: 'Chuyển hướng', message: 'Đã đến lúc bạn nên rẽ sang một hướng đi khác.' },
  { id: 103, title: 'Tăng tốc', message: 'Đừng chần chừ nữa, hãy đẩy nhanh tiến độ lên.' },
  {
    id: 104,
    title: 'Kỷ luật bản thân',
    message: 'Bạn cần phải nghiêm khắc hơn với chính mình trong chuyện này.',
  },
  { id: 105, title: 'Chịu trách nhiệm', message: 'Hãy dũng cảm đứng ra nhận lấy trách nhiệm.' },
  {
    id: 106,
    title: 'Sự thích nghi',
    message: 'Hoàn cảnh đã thay đổi, bạn cũng cần phải thích nghi.',
  },
  {
    id: 107,
    title: 'Giữ vững lập trường',
    message: 'Đừng lung lay, hãy kiên định với quan điểm của bạn.',
  },
  { id: 108, title: 'Khoảng lặng', message: 'Sự im lặng chính là câu trả lời tốt nhất lúc này.' },
  { id: 109, title: 'Sự độc lập', message: 'Tự mình giải quyết là phương án tối ưu nhất.' },
  {
    id: 110,
    title: 'Người đồng hành',
    message: 'Đừng đi một mình, hãy tìm người sát cánh cùng bạn.',
  },
  {
    id: 111,
    title: 'Thoát khỏi lối mòn',
    message: 'Đừng làm theo cách cũ nếu muốn có kết quả mới.',
  },
  {
    id: 112,
    title: 'Tầm nhìn xa',
    message: 'Hãy nhìn vào bức tranh toàn cảnh thay vì những tiểu tiết.',
  },
  {
    id: 113,
    title: 'Từ chối khéo',
    message: 'Hãy học cách nói Không một cách dứt khoát nhưng lịch sự.',
  },
  {
    id: 114,
    title: 'Giới hạn bản thân',
    message: 'Bạn đang tự vạch ra giới hạn cho chính mình, hãy phá vỡ nó.',
  },
  {
    id: 115,
    title: 'Lòng dũng cảm',
    message: 'Đây là lúc cần đến lòng can đảm phi thường của bạn.',
  },
  { id: 116, title: 'Sự nhượng bộ', message: 'Lùi một bước trời cao biển rộng.' },
  { id: 117, title: 'Quan sát kỹ', message: 'Hãy lặng lẽ quan sát tình hình thêm một thời gian.' },
  {
    id: 118,
    title: 'Nói lên suy nghĩ',
    message: 'Đừng giữ trong lòng, hãy nói ra điều bạn thực sự nghĩ.',
  },
  { id: 119, title: 'Lòng tin', message: 'Bạn đang trao niềm tin nhầm người.' },
  { id: 120, title: 'Gắn kết', message: 'Hãy củng cố lại các mối quan hệ xung quanh bạn.' },
  { id: 121, title: 'Cảm xúc tiêu cực', message: 'Đừng để sự giận dữ làm mờ mắt bạn.' },
  { id: 122, title: 'Cơ hội thứ hai', message: 'Bạn sẽ có cơ hội để làm lại từ đầu.' },
  {
    id: 123,
    title: 'Sự hy sinh',
    message: 'Bạn sẽ phải đánh đổi một thứ gì đó để đạt được mục đích.',
  },
  {
    id: 124,
    title: 'Chờ đợi phản hồi',
    message: 'Đừng hối thúc, hãy kiên nhẫn đợi đối phương lên tiếng.',
  },
  { id: 125, title: 'Tự do', message: 'Hãy cởi trói cho những suy nghĩ đang kìm hãm bạn.' },
  {
    id: 126,
    title: 'Tìm kiếm sự đồng thuận',
    message: 'Đừng tự quyết, hãy thảo luận cùng mọi người.',
  },
  {
    id: 127,
    title: 'Trực giác mách bảo',
    message: 'Điều đầu tiên nảy ra trong đầu bạn chính là đáp án.',
  },
  { id: 128, title: 'Sự cảnh giác', message: 'Hãy đề phòng những lời đường mật.' },
  { id: 129, title: 'Tái đánh giá', message: 'Giá trị của sự việc này không như bạn tưởng tượng.' },
  { id: 130, title: 'Sự tự mãn', message: 'Đừng vội ngủ quên trên chiến thắng.' },
  { id: 131, title: 'Sự chân thành', message: 'Sự thật lòng của bạn sẽ chạm đến trái tim họ.' },
  { id: 132, title: 'Loại bỏ rào cản', message: 'Hãy mạnh tay cắt bỏ những thứ cản đường bạn.' },
  { id: 133, title: 'Thời cơ chín muồi', message: 'Mọi điều kiện đều đã hoàn hảo, hãy chớp lấy.' },
  { id: 134, title: 'Tránh đối đầu', message: 'Đừng tạo thêm kẻ thù vào lúc này.' },
  { id: 135, title: 'Cái nhìn thực tế', message: 'Hãy bước ra khỏi sự ảo tưởng của chính mình.' },
  {
    id: 136,
    title: 'Nguồn cảm hứng',
    message: 'Bạn sẽ tìm thấy câu trả lời ở một nơi không ngờ tới.',
  },
  { id: 137, title: 'Tin đồn', message: 'Đừng tin vào những lời đồn thổi vô căn cứ.' },
  {
    id: 138,
    title: 'Lời hứa',
    message: 'Hãy thực hiện những gì bạn đã hứa trước khi bắt đầu việc mới.',
  },
  { id: 139, title: 'Sự kiên trì', message: 'Thành công chỉ dành cho những ai không bỏ cuộc.' },
  {
    id: 140,
    title: 'Phân chia công việc',
    message: 'Bạn không thể ôm đồm mọi thứ, hãy chia sẻ gánh nặng.',
  },
  {
    id: 141,
    title: 'Trân trọng hiện tại',
    message: 'Đừng mải nhìn về tương lai mà bỏ lỡ giây phút này.',
  },
  { id: 142, title: 'Sự tò mò', message: 'Hãy đặt câu hỏi, bạn sẽ khám phá ra nhiều điều thú vị.' },
  {
    id: 143,
    title: 'Làm theo luật',
    message: 'Hãy tuân thủ nghiêm ngặt các nguyên tắc đã đặt ra.',
  },
  { id: 144, title: 'Biết điểm dừng', message: 'Đừng quá tham lam, biết đủ mới là khôn ngoan.' },
  { id: 145, title: 'Ngủ một giấc', message: 'Mọi chuyện sẽ rõ ràng hơn vào sáng ngày mai.' },
  { id: 146, title: 'Phản ứng tự nhiên', message: 'Cứ để mọi chuyện diễn ra theo lẽ tự nhiên.' },
  {
    id: 147,
    title: 'Bất đồng quan điểm',
    message: 'Chấp nhận sự khác biệt là chìa khóa của vấn đề.',
  },
  {
    id: 148,
    title: 'Ghi chép',
    message: 'Hãy viết những suy nghĩ của bạn ra giấy để nhìn nhận rõ hơn.',
  },
  { id: 149, title: 'Bỏ qua mặc cảm', message: 'Đừng để những sai lầm trong quá khứ ám ảnh bạn.' },
  {
    id: 150,
    title: 'Bảo vệ bản thân',
    message: 'Hãy thiết lập những ranh giới cá nhân vững chắc.',
  },
  {
    id: 151,
    title: 'Làm điều đúng đắn',
    message: 'Dù khó khăn, hãy chọn con đường đàng hoàng nhất.',
  },
  {
    id: 152,
    title: 'Kết nối thiên nhiên',
    message: 'Không gian mở sẽ mang lại cho bạn sự thông suốt.',
  },
  { id: 153, title: 'Tránh vòng vo', message: 'Hãy đi thẳng vào trọng tâm của vấn đề.' },
  { id: 154, title: 'Sự đồng cảm', message: 'Sự thấu hiểu sẽ giúp hóa giải những khúc mắc.' },
  { id: 155, title: 'Sự may rủi', message: 'Đôi khi bạn cần phải liều lĩnh một chút.' },
  {
    id: 156,
    title: 'Chuẩn bị tâm lý',
    message: 'Kết quả có thể không ngọt ngào như bạn mong đợi.',
  },
  { id: 157, title: 'Khách quan', message: 'Đừng để tình cảm cá nhân xen vào quyết định này.' },
  {
    id: 158,
    title: 'Tôn trọng đối thủ',
    message: 'Hãy đánh giá đúng thực lực của những người xung quanh.',
  },
  { id: 159, title: 'Mảnh ghép còn thiếu', message: 'Bạn sắp tìm thấy thông tin quan trọng nhất.' },
  { id: 160, title: 'Hành động thầm lặng', message: 'Cứ lẳng lặng mà làm, đừng phô trương.' },
  {
    id: 161,
    title: 'Sự ưu tiên',
    message: 'Xác định lại xem điều gì là quan trọng nhất với bạn lúc này.',
  },
  { id: 162, title: 'Bỏ ngoài tai', message: 'Mặc kệ những lời phán xét của người khác.' },
  { id: 163, title: 'Niềm kiêu hãnh', message: 'Đừng để cái tôi cản trở thành công của bạn.' },
  { id: 164, title: 'Sức mạnh nội tại', message: 'Bạn mạnh mẽ hơn bạn tưởng rất nhiều.' },
  { id: 165, title: 'Khác biệt', message: 'Chính sự khác biệt sẽ làm nên điểm nhấn của bạn.' },
  { id: 166, title: 'Chắp vá', message: 'Đừng cố sửa chữa những thứ đã vỡ nát hoàn toàn.' },
  { id: 167, title: 'Quên đi', message: 'Điều tốt nhất bây giờ là lãng quên nó đi.' },
  {
    id: 168,
    title: 'Thận trọng tài chính',
    message: 'Đừng vung tiền vào những thứ không chắc chắn.',
  },
  { id: 169, title: 'Sự phản bội', message: 'Cẩn thận với những người tỏ ra quá thân thiết.' },
  { id: 170, title: 'Bảo mật', message: 'Thông tin này cần được giữ kín tuyệt đối.' },
  { id: 171, title: 'Tận hưởng', message: 'Đừng quá căng thẳng, hãy tận hưởng quá trình này.' },
  { id: 172, title: 'Bước ngoặt', message: 'Đây chính là cột mốc quan trọng trong cuộc đời bạn.' },
  {
    id: 173,
    title: 'Tập trung vào giải pháp',
    message: 'Đừng than vãn nữa, hãy tìm cách giải quyết.',
  },
  {
    id: 174,
    title: 'Làm mới không gian',
    message: 'Thay đổi môi trường xung quanh sẽ thay đổi cục diện.',
  },
  {
    id: 175,
    title: 'Sự ngẫu nhiên',
    message: 'Hãy tung đồng xu để quyết định nếu bạn quá băn khoăn.',
  },
  {
    id: 176,
    title: 'Chấp nhận khuyết điểm',
    message: 'Không có gì là hoàn hảo, hãy chấp nhận những tì vết.',
  },
  { id: 177, title: 'Lòng biết ơn', message: 'Một lời cảm ơn chân thành sẽ mở ra nhiều cánh cửa.' },
  { id: 178, title: 'Nghỉ ngơi', message: 'Cơ thể bạn đang báo động, hãy nghỉ ngơi.' },
  { id: 179, title: 'Không can thiệp', message: 'Hãy đứng ngoài cuộc và để họ tự giải quyết.' },
  { id: 180, title: 'Sự rõ ràng', message: 'Yêu cầu họ giải thích mọi thứ thật minh bạch.' },
  { id: 181, title: 'Bỏ cuộc', message: 'Từ bỏ đúng lúc cũng là một loại trí tuệ.' },
  {
    id: 182,
    title: 'Tin tưởng vào hệ thống',
    message: 'Cứ tuân theo quy trình, mọi thứ sẽ ổn thỏa.',
  },
  {
    id: 183,
    title: 'Hành động quyết liệt',
    message: 'Phải có những biện pháp mạnh tay mới giải quyết được.',
  },
  { id: 184, title: 'Khảo sát', message: 'Hãy lắng nghe số đông trước khi ra quyết định.' },
  {
    id: 185,
    title: 'Thay đổi tư duy',
    message: 'Nếu không thay đổi suy nghĩ, kết quả vẫn sẽ như vậy.',
  },
  { id: 186, title: 'Bảo vệ quan điểm', message: 'Đừng nhượng bộ nếu bạn biết mình đang đúng.' },
  { id: 187, title: 'Đánh lạc hướng', message: 'Vấn đề thực sự không nằm ở đây.' },
  {
    id: 188,
    title: 'Sự trùng hợp',
    message: 'Không có sự trùng hợp nào ngẫu nhiên cả, đó là dấu hiệu.',
  },
  { id: 189, title: 'Giữ lời', message: 'Uy tín là thứ quan trọng nhất của bạn lúc này.' },
  { id: 190, title: 'Lòng trắc ẩn', message: 'Hãy đối xử với họ bằng sự từ bi và khoan dung.' },
  { id: 191, title: 'Độc đáo', message: 'Câu trả lời nằm ở sự sáng tạo điên rồ nhất.' },
  { id: 192, title: 'Trở về cơ bản', message: 'Hãy quay lại với những giá trị cốt lõi ban đầu.' },
  { id: 193, title: 'Lảng tránh', message: 'Trốn tránh không làm vấn đề biến mất.' },
  { id: 194, title: 'Sự tỉnh táo', message: 'Hãy uống một cốc nước lạnh và nhìn nhận lại.' },
  { id: 195, title: 'Gương mặt thật', message: 'Chiếc mặt nạ sắp rơi xuống.' },
  { id: 196, title: 'Sự trọn vẹn', message: 'Mọi thứ đã kết thúc một cách trọn vẹn.' },
  { id: 197, title: 'Hiểu lầm', message: 'Có một sự hiểu lầm nghiêm trọng ở đây.' },
  { id: 198, title: 'Cơ hội cuối', message: 'Đây là chuyến tàu cuối cùng, đừng để lỡ.' },
  { id: 199, title: 'Sự công nhận', message: 'Những nỗ lực của bạn cuối cùng cũng được ghi nhận.' },
  {
    id: 200,
    title: 'Tin vào chính mình',
    message: 'Chỉ bạn mới biết điều gì là tốt nhất cho mình.',
  },
]
